### PR TITLE
migration to staging environment

### PR DESCRIPTION
**Pull request by chiamaka-ukwuoma**

### CODE REVIEW

**Review by adedolapo-olutuyo — APPROVED** [review]
Never seen a game changing migration than this!!!

**Review by adedolapo-olutuyo — APPROVED** [review]
Never seen a game changing migration than this!!!

**Review by mikuenob — APPROVED** [review]
LGTM👍

**Review by jodugbose — APPROVED** [review]
Omo!!!!!! You too sab👏👏👏👏👏

**Pull request merged**
